## YAML Template.
---
services:
  registry-discovery:
    container_name: id-eureka
    image: eurekaserver_image:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M 

  product:
    container_name: bd-product
    image: product_image:0.0.1-SNAPSHOT
    environment:
       - EUREKA_SERVER=http://registry-discovery:8761/eureka/
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -EUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
    ports:
      - 8081:8081

  customer:
    container_name: bd-customer
    image: customer_image:0.0.1-SNAPSHOT   
    environment:
      - EUREKA_SERVER=http://registry-discovery:8761/eureka/
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M

    depends_on:
      - registry-discovery

  configserver:
    container_name: bd-configserver
    image: configserver_image:0.0.1-SNAPSHOT
    environment:
      - EUREKA_SERVER=http://registry-discovery:8761/eureka/
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DREPOSITORY_PATH=/repo
    volumes:
      - /d/Proyectos/SpringBoot/paymentchainparent/config-server-repo:/repo
    depends_on:
      - registry-discovery
    ports:
      - 8888:8888

  admin_image:
    container_name: bd-admin_image
    image: admin_image:0.0.1-SNAPSHOT   
    environment:
      - EUREKA_SERVER=http://registry-discovery:8761/eureka/
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M

    depends_on:
      - registry-discovery
    ports:
      - 8062:8062

  apigateway_image:
      container_name: id_apigateway_image
      image: apigateway_image:0.0.1-SNAPSHOT   
      environment:
        - EUREKA_SERVER=http://registry-discovery:8761/eureka/
        - JAVA_OPTS=
             -Xms256M 
             -Xmx256M

      depends_on:
        - registry-discovery
      ports:
        - 8080:8080


  invoice_image:
    container_name: bd-invoice_image
    image: invoice_image:0.0.1-SNAPSHOT   
    environment:
      - EUREKA_SERVER=http://registry-discovery:8761/eureka/
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M

    depends_on:
      - registry-discovery
    ports:
      - 8084:8084

  transaction_image:
    container_name: bd-transaction_image
    image: transaction_image:0.0.1-SNAPSHOT   
    environment:
      - EUREKA_SERVER=http://registry-discovery:8761/eureka/
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M

    depends_on:
      - registry-discovery
    ports:
      - 8082:8082
    
  kaycloackadapter_image:
    container_name: id-kaycloackadapter_image
    image: kaycloackadapter_image:0.0.1-SNAPSHOT   
    environment:
      - EUREKA_SERVER=http://registry-discovery:8761/eureka/
      - KEYCLOACK_SERVER=http://keycloak_server:8080/realms/
      - KEYCLOACK_REAL_ID=UOTF61lV1iVdmFd0mRnDbN_KnVsE8SySZlli0Eqm8_A
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256Ms

    depends_on:
      - registry-discovery
    ports:
      - 8088:8088
    
  postgres_db:
    container_name: postgres
    image: postgres:latest
    ports:
        - 5432:5432
    volumes:
        - ./dbfiles:/docker-entrypoint-initdb.d
        - ./postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: qwerty
        POSTGRES_DB: postgres


  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "qwerty"
    ports:
      - 80:80
    depends_on:
      - postgres_db
     
      #BD para H2
  keycloak_server:
    container_name: id_keycloakserver
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
        - 8091:8080
      #BD para postgres
  #keycloak:
  #  container_name: keycloak
   # image: quay.io/keycloak/keycloak:24.0.3
   # command: start-dev
   # ports:
   #   - 8080:8080
   # environment:
   #   KC_DB: postgres
   #   KC_DB_URL: jdbc:postgresql://postgres_db:5432/postgres
   #   KC_DB_USERNAME: postgres
   #   KC_DB_PASSWORD: qwerty
   #   KEYCLOAK_ADMIN: admin
   #   KEYCLOAK_ADMIN_PASSWORD: admin
   # depends_on:
   #   - postgres_db


