## YAML Template.
---
# swagger-ui custom path
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        enabled: false

server:
    port: 49157
    
custom:
    activeprofileName: production
    

# Tipo de base de datos (MySQL como ejemplo)
spring:
    datasource:
        url: jdbc:h2:mem:customer
        username: sa
        password: qwerty
        driver-class-name: org.h2.Driver
    h2:
        console.enabled: true
    jpa:
        show-sql: true
    